// project_1 - Generated by Labelle GUI
//
// This is the main entry point for your game.
// Edit this file to customize game initialization and behavior.

const std = @import("std");
const engine = @import("labelle-engine");
const labelle = @import("labelle");

// Import components from the components/ folder
// Example: const velocity = @import("components/velocity.zig");

// Component registry - add your components here
const Components = engine.ComponentRegistry(struct {
    // Example: pub const Velocity = velocity.Velocity;
});

// Prefab registry - add your prefabs here
const Prefabs = engine.PrefabRegistry(.{});

// Script registry - add your scripts here
const Scripts = engine.ScriptRegistry(struct {});

// Scene loader type
const Loader = engine.SceneLoader(Prefabs, Components, Scripts);

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    // Initialize game with the Game facade
    var game = try engine.Game.init(allocator, .{
        .window = .{
            .width = 1280,
            .height = 720,
            .title = "project_1",
        },
        .clear_color = .{ .r = 30, .g = 35, .b = 45 },
    });
    defer game.deinit();

    // Register scenes - import your scene .zon files here
    try game.registerSceneSimple("main", Loader, @import("scenes/main.zon"));

    // Start with main scene
    try game.setScene("main");

    // Run the game loop
    try game.run();
}
